// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Users struct {
	ID            uuid.UUID          `json:"id"`
	FirstName     string             `json:"first_name"`
	LastName      string             `json:"last_name"`
	Email         string             `json:"email"`
	PhoneNumber   pgtype.Text        `json:"phone_number"`
	StreetAddress string             `json:"street_address"`
	City          string             `json:"city"`
	State         string             `json:"state"`
	Country       string             `json:"country"`
	Username      string             `json:"username"`
	PasswordHash  []byte             `json:"password_hash"`
	AcceptTerms   bool               `json:"accept_terms"`
	Newsletter    bool               `json:"newsletter"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	Version       int32              `json:"version"`
}
