// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const checkEmailExists = `-- name: CheckEmailExists :one
SELECT EXISTS(SELECT 1 FROM users WHERE email = $1)
`

func (q *Queries) CheckEmailExists(ctx context.Context, email string) (bool, error) {
	row := q.db.QueryRow(ctx, checkEmailExists, email)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const checkUsernameExists = `-- name: CheckUsernameExists :one
SELECT EXISTS(SELECT 1 FROM users WHERE username = $1)
`

func (q *Queries) CheckUsernameExists(ctx context.Context, username string) (bool, error) {
	row := q.db.QueryRow(ctx, checkUsernameExists, username)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    first_name,
    last_name,
    email,
    phone_number,
    street_address,
    city,
    state,
    country,
    username,
    password_hash,
    accept_terms,
    newsletter
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
RETURNING id, first_name, last_name, email, phone_number, street_address, city, state, country, username, password_hash, accept_terms, newsletter, created_at, updated_at, version
`

type CreateUserParams struct {
	FirstName     string      `json:"first_name"`
	LastName      string      `json:"last_name"`
	Email         string      `json:"email"`
	PhoneNumber   pgtype.Text `json:"phone_number"`
	StreetAddress string      `json:"street_address"`
	City          string      `json:"city"`
	State         string      `json:"state"`
	Country       string      `json:"country"`
	Username      string      `json:"username"`
	PasswordHash  []byte      `json:"password_hash"`
	AcceptTerms   bool        `json:"accept_terms"`
	Newsletter    bool        `json:"newsletter"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (Users, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.FirstName,
		arg.LastName,
		arg.Email,
		arg.PhoneNumber,
		arg.StreetAddress,
		arg.City,
		arg.State,
		arg.Country,
		arg.Username,
		arg.PasswordHash,
		arg.AcceptTerms,
		arg.Newsletter,
	)
	var i Users
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.PhoneNumber,
		&i.StreetAddress,
		&i.City,
		&i.State,
		&i.Country,
		&i.Username,
		&i.PasswordHash,
		&i.AcceptTerms,
		&i.Newsletter,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, first_name, last_name, email, phone_number, street_address, city, state, country, username, password_hash, accept_terms, newsletter, created_at, updated_at, version FROM users WHERE email = $1 LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (Users, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i Users
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.PhoneNumber,
		&i.StreetAddress,
		&i.City,
		&i.State,
		&i.Country,
		&i.Username,
		&i.PasswordHash,
		&i.AcceptTerms,
		&i.Newsletter,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, first_name, last_name, email, phone_number, street_address, city, state, country, username, password_hash, accept_terms, newsletter, created_at, updated_at, version FROM users WHERE username = $1 LIMIT 1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (Users, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i Users
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.PhoneNumber,
		&i.StreetAddress,
		&i.City,
		&i.State,
		&i.Country,
		&i.Username,
		&i.PasswordHash,
		&i.AcceptTerms,
		&i.Newsletter,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}
