export const COUNTRIES = [
    {
        code: 'US',
        name: 'United States',
        tlds: ['.us', '.com', '.net', '.org', '.edu', '.gov'],
    },
    {
        code: 'UK',
        name: 'United Kingdom',
        tlds: ['.uk', '.co.uk', '.org.uk', '.gov.uk', '.ac.uk'],
    },
    { code: 'CA', name: 'Canada', tlds: ['.ca'] },
    {
        code: 'AU',
        name: 'Australia',
        tlds: ['.au', '.com.au', '.net.au', '.org.au', '.edu.au'],
    },
    { code: 'DE', name: 'Germany', tlds: ['.de'] },
    { code: 'FR', name: 'France', tlds: ['.fr'] },
    { code: 'JP', name: 'Japan', tlds: ['.jp'] },
    { code: 'IN', name: 'India', tlds: ['.in', '.co.in', '.org.in', '.net.in'] },
    { code: 'BR', name: 'Brazil', tlds: ['.br'] },
    { code: 'IT', name: 'Italy', tlds: ['.it'] },
    { code: 'ES', name: 'Spain', tlds: ['.es'] },
    { code: 'NL', name: 'Netherlands', tlds: ['.nl'] },
    { code: 'SE', name: 'Sweden', tlds: ['.se'] },
    { code: 'CH', name: 'Switzerland', tlds: ['.ch'] },
    { code: 'NO', name: 'Norway', tlds: ['.no'] },
    { code: 'DK', name: 'Denmark', tlds: ['.dk'] },
    { code: 'FI', name: 'Finland', tlds: ['.fi'] },
] as const

export const STATES = {
    US: [
        { code: 'AL', name: 'Alabama' },
        { code: 'AK', name: 'Alaska' },
        { code: 'AZ', name: 'Arizona' },
        { code: 'AR', name: 'Arkansas' },
        { code: 'CA', name: 'California' },
        { code: 'CO', name: 'Colorado' },
        { code: 'CT', name: 'Connecticut' },
        { code: 'DE', name: 'Delaware' },
        { code: 'FL', name: 'Florida' },
        { code: 'GA', name: 'Georgia' },
        { code: 'HI', name: 'Hawaii' },
        { code: 'ID', name: 'Idaho' },
        { code: 'IL', name: 'Illinois' },
        { code: 'IN', name: 'Indiana' },
        { code: 'IA', name: 'Iowa' },
        { code: 'KS', name: 'Kansas' },
        { code: 'KY', name: 'Kentucky' },
        { code: 'LA', name: 'Louisiana' },
        { code: 'ME', name: 'Maine' },
        { code: 'MD', name: 'Maryland' },
        { code: 'MA', name: 'Massachusetts' },
        { code: 'MI', name: 'Michigan' },
        { code: 'MN', name: 'Minnesota' },
        { code: 'MS', name: 'Mississippi' },
        { code: 'MO', name: 'Missouri' },
        { code: 'MT', name: 'Montana' },
        { code: 'NE', name: 'Nebraska' },
        { code: 'NV', name: 'Nevada' },
        { code: 'NH', name: 'New Hampshire' },
        { code: 'NJ', name: 'New Jersey' },
        { code: 'NM', name: 'New Mexico' },
        { code: 'NY', name: 'New York' },
        { code: 'NC', name: 'North Carolina' },
        { code: 'ND', name: 'North Dakota' },
        { code: 'OH', name: 'Ohio' },
        { code: 'OK', name: 'Oklahoma' },
        { code: 'OR', name: 'Oregon' },
        { code: 'PA', name: 'Pennsylvania' },
        { code: 'RI', name: 'Rhode Island' },
        { code: 'SC', name: 'South Carolina' },
        { code: 'SD', name: 'South Dakota' },
        { code: 'TN', name: 'Tennessee' },
        { code: 'TX', name: 'Texas' },
        { code: 'UT', name: 'Utah' },
        { code: 'VT', name: 'Vermont' },
        { code: 'VA', name: 'Virginia' },
        { code: 'WA', name: 'Washington' },
        { code: 'WV', name: 'West Virginia' },
        { code: 'WI', name: 'Wisconsin' },
        { code: 'WY', name: 'Wyoming' },
    ],
    UK: [
        { code: 'ENG', name: 'England' },
        { code: 'SCT', name: 'Scotland' },
        { code: 'WLS', name: 'Wales' },
        { code: 'NIR', name: 'Northern Ireland' },
    ],
    CA: [
        { code: 'AB', name: 'Alberta' },
        { code: 'BC', name: 'British Columbia' },
        { code: 'MB', name: 'Manitoba' },
        { code: 'NB', name: 'New Brunswick' },
        { code: 'NL', name: 'Newfoundland and Labrador' },
        { code: 'NS', name: 'Nova Scotia' },
        { code: 'ON', name: 'Ontario' },
        { code: 'PE', name: 'Prince Edward Island' },
        { code: 'QC', name: 'Quebec' },
        { code: 'SK', name: 'Saskatchewan' },
        { code: 'NT', name: 'Northwest Territories' },
        { code: 'NU', name: 'Nunavut' },
        { code: 'YT', name: 'Yukon' },
    ],
    AU: [
        { code: 'ACT', name: 'Australian Capital Territory' },
        { code: 'NSW', name: 'New South Wales' },
        { code: 'NT', name: 'Northern Territory' },
        { code: 'QLD', name: 'Queensland' },
        { code: 'SA', name: 'South Australia' },
        { code: 'TAS', name: 'Tasmania' },
        { code: 'VIC', name: 'Victoria' },
        { code: 'WA', name: 'Western Australia' },
    ],
    DE: [
        { code: 'BW', name: 'Baden-Württemberg' },
        { code: 'BY', name: 'Bavaria' },
        { code: 'BE', name: 'Berlin' },
        { code: 'BB', name: 'Brandenburg' },
        { code: 'HB', name: 'Bremen' },
        { code: 'HH', name: 'Hamburg' },
        { code: 'HE', name: 'Hesse' },
        { code: 'NI', name: 'Lower Saxony' },
        { code: 'MV', name: 'Mecklenburg-Vorpommern' },
        { code: 'NW', name: 'North Rhine-Westphalia' },
        { code: 'RP', name: 'Rhineland-Palatinate' },
        { code: 'SL', name: 'Saarland' },
        { code: 'SN', name: 'Saxony' },
        { code: 'ST', name: 'Saxony-Anhalt' },
        { code: 'SH', name: 'Schleswig-Holstein' },
        { code: 'TH', name: 'Thuringia' },
    ],
} as const

export const STEPS = [
    { number: 1, title: 'Personal Info' },
    { number: 2, title: 'Address' },
    { number: 3, title: 'Account Setup' },
    { number: 4, title: 'Review' },
] as const
